version: "3"
services:
  web:
    image: nginx:1.15.6
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel-app:/var/www/html
  app:
    build: ./docker/php
    volumes:
      - ./laravel-app:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: matching-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "2002:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
